//! Runtime-generated local test identities; never commit private-key fixtures.

use std::path::PathBuf;

use rcgen::{
    BasicConstraints, CertificateParams, ExtendedKeyUsagePurpose, IsCa, Issuer, KeyPair,
    KeyUsagePurpose,
};

// This shared fixture is compiled into both the library and integration test
// binaries; the library tests do not need the server's identity.
#[allow(dead_code)]
pub(crate) struct Certificates {
    pub(crate) directory: PathBuf,
    pub(crate) ca: String,
    pub(crate) server_cert: String,
    pub(crate) server_key: String,
    pub(crate) client_cert: String,
    pub(crate) client_key: String,
}

impl Certificates {
    pub(crate) fn new() -> Self {
        let mut ca_params = CertificateParams::new(Vec::<String>::new()).unwrap();
        ca_params.is_ca = IsCa::Ca(BasicConstraints::Unconstrained);
        ca_params.key_usages = vec![KeyUsagePurpose::KeyCertSign, KeyUsagePurpose::CrlSign];
        let ca_key = KeyPair::generate().unwrap();
        let ca = ca_params.self_signed(&ca_key).unwrap().pem();
        let issuer = Issuer::new(ca_params, ca_key);
        let leaf = |role| {
            let mut params = CertificateParams::new(vec!["spanner.test".into()]).unwrap();
            params.key_usages = vec![KeyUsagePurpose::DigitalSignature];
            params.extended_key_usages = vec![role];
            let key = KeyPair::generate().unwrap();
            let cert = params.signed_by(&key, &issuer).unwrap().pem();
            (cert, key.serialize_pem())
        };
        let (server_cert, server_key) = leaf(ExtendedKeyUsagePurpose::ServerAuth);
        let (client_cert, client_key) = leaf(ExtendedKeyUsagePurpose::ClientAuth);
        let directory = std::env::temp_dir().join(format!(
            "duckdb-spanner-tls-{}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos(),
            {
                static NEXT: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
                NEXT.fetch_add(1, std::sync::atomic::Ordering::Relaxed)
            }
        ));
        std::fs::create_dir(&directory).unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&directory, std::fs::Permissions::from_mode(0o700)).unwrap();
        }
        let result = Self {
            directory,
            ca,
            server_cert,
            server_key,
            client_cert,
            client_key,
        };
        for (name, contents) in [
            ("ca.pem", &result.ca),
            ("client.pem", &result.client_cert),
            ("client.key", &result.client_key),
        ] {
            std::fs::write(result.directory.join(name), contents).unwrap();
        }
        result
    }

    pub(crate) fn setting(&self, name: &str) -> Option<String> {
        let filename = match name {
            "spanner_tls_root_ca_file" => "ca.pem",
            "spanner_tls_client_cert_file" => "client.pem",
            "spanner_tls_client_key_file" => "client.key",
            "spanner_tls_server_name" => return Some("spanner.test".into()),
            _ => return None,
        };
        Some(self.directory.join(filename).to_str().unwrap().to_owned())
    }
}

impl Drop for Certificates {
    fn drop(&mut self) {
        // Only files generated by this fixture, not user resources.
        let _ = std::fs::remove_dir_all(&self.directory);
    }
}
